#!/bin/bash

# Clearing the space
clear

# Get the message
hostname=$(hostname)
name=$(toilet -f "bigmono12" $hostname)

# Get CPU usage
cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}')

# Get memory usage
mem_info=$(free -m | awk 'NR==2{printf "%.2f", $3*100/$2}')
mem_usage="$mem_info%"

# Get swap usage
swap_info=$(free -m | awk 'NR==3{printf "%.2f", $3*100/$2}')
swap_usage="$swap_info%"

# Get disk usage
disk_usage=$(df -h | awk '$NF=="/"{printf "%.2f", $3*100/$2}')
disk_usage="$disk_usage%"

# Get the message
message=$(cat << EOF

$name
**************************
** CPU    Usage: $cpu_usage **
** Memory Usage: $mem_usage **
** Swap   Usage: $swap_usage **
** Disk   Usage: $disk_usage **
**************************
EOF
)

# Great Effect
function colorize_text() {
  local input_text="$@"
  local pos=0

  for ((i=0; i<${#input_text}; i++)); do
    pos=$((pos % 6))
    case $pos in
      0) color_code="196" ;;
      1) color_code="202" ;;
      2) color_code="226" ;;
      3) color_code="46" ;;
      4) color_code="21" ;;
      5) color_code="93" ;;
    esac

    echo -en "\033[38;5;${color_code}m${input_text:$i:1}"
    pos=$((pos + 1))
  done
}


# Display the message

printf "%s\n" "$message" | while IFS= read -r line; do
  colorize_text "$line"
  echo -e "\033[0m"
done