services:
  debian_server:
    container_name: server_${NEW_HOSTNAME}
    image: debian:latest
    hostname: ${NEW_HOSTNAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEW_USER=${NEW_USER}
      - NEW_HOSTNAME=${NEW_HOSTNAME}
      - NEW_PASSWORD=${NEW_PASSWORD}
    # command: /config.sh
    # command: ["/bin/bash", "-c", "while true; do sleep 1; done", "&"]
    ports:
      - "2223:22"
      - "2224:25565"
    volumes:
      - ./data:/${NEW_USER}
    restart: unless-stopped